### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by BookXHD** [metatron-app/metatron-discovery#1856]
HELP!!! Can you upload your dockerfile which used to build the existing Metatron docker images ?

**Comment by alchan-lee** [comment]
Hi @BookXHD.

I attach [this file](https://github.com/metatron-app/metatron-discovery/files/3078950/Dockerfile.txt) what I use for building a discovery image.
(It has .txt extension because of Github's policy. It will be moved into the git repo soon)

FYI, it is possible to execute reverse engineering of a docker image using this command :
`docker history <image> --no-trunc`

**Comment by BookXHD** [comment]
@alchan-lee Thanks ! That does help me ,but now i get another question: when i Running the Metatron Binary and making the CUSTOM INSTALL, after export METATRON_HOME and shell "sh metatron.sh --init start", there appears an error in /logs/xxx.out file which is "Error: Could not find or load main class org.springframework.boot.loader.PropertiesLauncher", how should i do to resolve this?
