### ISSUE TITLE
[ARCH QUESTION] Kylin as second engine

### ISSUE THREAD

**Issue by ocoka** [metatron-app/metatron-discovery#1897]
Hello, we have a question, we use *Apache Kylin* as BI engine, and now interested is it possible to add *Kylin* as **second engine** to *Metatron Discovery* ?
If in theory it is possible, can you tell what point of integration or modification in code base we should to conside.

Thank you.

**Comment by kyungtaak** [comment]
@ocoka First of all thank you for your interest in "metatron discovery". :) 
It is optimized for druid we customized. In this reason, I doubt if it will work because it is not made considering the second engine.

But, as a theoretical approach, it may be possible to change the data source creation part and the data source query part. Actions related to the druid engine were collected in the "app.metatron.discovery.domain.engin" package.

If I'm in your situation, I'll try to manually configure the data source generation and change the data query part such as search or candidate method. If so, I would expect to see a simple dashboard.

In this case, you should refer to the "app.metatron.discovery.domain.engine.QueryService" interface.

I do not know if your question was answered. Still, I strongly recommend that you use druid, but if you have to use kylin, It's another option, you can create a data connection extension for kylin and then load the datasource using db connection mode from kylin.

**Comment by ocoka** [comment]
@kyungtaak Thank you, your answer is important for us, in couple of past days we also come to decision that it is better to use Kylin jdbc connection mode, and your words confirmed our assumption. And we are further convinced that Druid is best engine, but idea about to make Kylin as optional second engine still present in mind, so we will look into detail about classes you've mentioned.

Thank you again.
