### ISSUE TITLE
Error in dataset generation in file type

### ISSUE THREAD

**Issue by jeongeunkwon** [metatron-app/metatron-discovery#2064]
**Describe the bug**
If I click the "Previous" button after uploading a file, I need to upload the file again from the beginning. It did not happen in version 3.2.0

**To Reproduce**
1. Go to Dataset and generate new dataset
2. Select data type - File
3. Upload a file
4. Click on Previous

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by joohokim1** [comment]
@jeongeunkwon The behavior has been changed because of new multi-file upload feature. When we upload only single file, we could keep the context by uploaded file name. But, for multi-file upload, this is impossible. So, we cannot keep the upload context any more. This is inevitable fall-back.
Closing issue.
