### ISSUE TITLE
about apache druid and metatron druid

### ISSUE THREAD

**Issue by FourSpaces** [metatron-app/metatron-discovery#2865]
Is there any idea to support Apache druid? Or does metatron druid incorporate the capabilities of Apache druid?

I didn't find the usage API and documentation for metatron druid. Does metatron druid provide kafka support?

Will Metatron druid be open source?

**Comment by kyungtaak** [comment]
@FourSpaces 
First, compared to apache druid, the basic query functionality is the same. However, since version 0.9.1, we've added some features to suit us. Please refer to the following link for more details : https://metatron.app/2018/06/15/skt-druid-features/

Unfortunately, the documentation of the added functionality is still poor. And kafka supports it. It is now possible to load real-time data sources using kafka in discovery. It has been added to the 3.4 rc2 version, so please try it once.

Finally, metatron druid plans to open source it. But We need more time. :(
