### ISSUE TITLE
cannot create datasource with new line data.

### ISSUE THREAD

**Issue by ufoscw** [metatron-app/metatron-discovery#547]
**Describe the bug**
데이터를 생성할때 일부 데이터가 줄바꿈 기호가 포함되어 있을때 쌍따옴표로 묶여져 있지만 파싱 에러 발생함.

**To Reproduce**
csv file : 
[20181025044945_e6630da7_0_ts.txt](https://github.com/metatron-app/metatron-discovery/files/2513954/20181025044945_e6630da7_0_ts.txt)

ingestion spec 
```
{
   "paths":[
      "/tmp/20181025044945_e6630da7_0_ts.csv"
   ],
   "schema":{
      "dataSource":"temporary_ingestion_1540442987025_rdgrt",
      "parser":{
         "type":"string",
         "parseSpec":{
            "format":"csv",
            "dimensionsSpec":{
               "dimensions":[
                  "job_log"
               ],
               "dimensionExclusions":[

               ],
               "spatialDimensions":[

               ]
            },
            "timestampSpec":{
               "column":"current_datetime",
               "format":"auto",
               "replaceWrongColumn":false
            },
            "columns":[
               "job_log",
               "current_datetime"
            ]
         }
      },
      "metricsSpec":[
         {
            "type":"count",
            "name":"count"
         }
      ],
      "granularitySpec":{
         "type":"uniform",
         "segmentGranularity":"MONTH",
         "queryGranularity":"DAY",
         "intervals":[
            "1970-01-01/2050-01-01"
         ],
         "rollup":true
      }
   }
}
```

Error
```
[
   {
      "error":"Unknown exception",
      "errorMessage":"Unable to parse row [\"]",
      "errorClass":"com.metamx.common.parsers.ParseException",
      "errorStack":[
         "com.metamx.common.parsers.CSVParser.parse(CSVParser.java:121)",
         "io.druid.data.input.impl.StringInputRowParser.parseString(StringInputRowParser.java:132)",
         "io.druid.data.input.impl.StringInputRowParser.parse(StringInputRowParser.java:75)",
         "io.druid.storage.hdfs.HdfsDataSegmentPusher$4.apply(HdfsDataSegmentPusher.java:284)",
         "io.druid.storage.hdfs.HdfsDataSegmentPusher$4.apply(HdfsDataSegmentPusher.java:279)",
         "io.druid.common.utils.Sequences$4.accumulate(Sequences.java:162)",
         "com.metamx.common.guava.MappedSequence.accumulate(MappedSequence.java:40)",
         "io.druid.storage.hdfs.HdfsDataSegmentPusher.write(HdfsDataSegmentPusher.java:327)",
         "io.druid.server.QueryResource$5.run(QueryResource.java:596)",
         "io.druid.server.BrokerQueryResource.loadToIndex(BrokerQueryResource.java:484)",
         "sun.reflect.GeneratedMethodAccessor131.invoke(Unknown Source)",
         "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
         "... more",
         "Caused by: au.com.bytecode.opencsv.CSVParser.parseLine(CSVParser.java:268)",
         "au.com.bytecode.opencsv.CSVParser.parseLine(CSVParser.java:178)",
         "com.metamx.common.parsers.CSVParser.parse(CSVParser.java:112)",
         "... more"
      ],
      "host":"localhost:8082",
      "serviceName":"druid/broker"
   }
]
```

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jeongeunkwon** [comment]
추가에러 내용입니다.
{"code":"EG0001","message":"Engine access error","details":"Fail to process response : [{\"error\":\"Unknown exception\",\"errorMessage\":\"Unable to parse row [20180626170107075,20180626170107075,20180626173308204,Android,7.0,1080*1920,1920,1080,KR,android,r0.5.0_c0.4.5,172.22.148.45,RAKEc-was02,708966f792a8ba2eca205deb8f5720e980dd6785,16.02.15:1.6.4:13,EenMPFKMcQC3yArVng7k17fITanxmJ2oGKx6N7+O79XHK+r2BvxdWNLrVYFT09r+3vjvjuk8lZgkLE5Lnc/uHw==,SM-N920S,samsung,SKTelecom,NOT WIFI,5.0.7.1900115,,,,,,,,,,tmap,\\\"+0hwTlhPvJBJACmWPF08gPEcrHa/yu2pHGPsil7fqT0=]\",\"errorClass\":\"com.metamx.common.parsers.ParseException\",\"errorStack\":[\"com.metamx.common.parsers.CSVParser.parse(CSVParser.java:121)\",\"io.druid.data.input.impl.StringInputRowParser.parseString(StringInputRowParser.java:132)\",\"io.druid.data.input.impl.StringInputRowParser.parse(StringInputRowParser.java:75)\",\"io.druid.storage.hdfs.HdfsDataSegmentPusher$4.apply(HdfsDataSegmentPusher.java:284)\",\"io.druid.storage.hdfs.HdfsDataSegmentPusher$4.apply(HdfsDataSegmentPusher.java:279)\",\"io.druid.common.utils.Sequences$4.accumulate(Sequences.java:162)\",\"com.metamx.common.guava.MappedSequence.accumulate(MappedSequence.java:40)\",\"io.druid.storage.hdfs.HdfsDataSegmentPusher.write(HdfsDataSegmentPusher.java:327)\",\"io.druid.server.QueryResource$5.run(QueryResource.java:596)\",\"io.druid.server.BrokerQueryResource.loadToIndex(BrokerQueryResource.java:484)\",\"sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\",\"sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\",\"... more\",\"Caused by: au.com.bytecode.opencsv.CSVParser.parseLine(CSVParser.java:268)\",\"au.com.bytecode.opencsv.CSVParser.parseLine(CSVParser.java:178)\",\"com.metamx.common.parsers.CSVParser.parse(CSVParser.java:112)\",\"... more\"],\"host\":\"druid-broker-0.druid-broker.metatron.svc.cluster.local:8082\",\"serviceName\":\"druid/stg/broker\"}]"}

csv file : 
[result_1540456800551.csv.txt](https://github.com/metatron-app/metatron-discovery/files/2514070/result_1540456800551.csv.txt)

**Comment by navis** [comment]
```json
  "parser":{
     "type":"csv.stream",
     "columns": [ "WKT","SIG_CD","SIG_ENG_NM","SIG_KOR_NM" ],
     "timestampSpec": { "column":"inspection_date", "format":"MM/dd/yyyy", "missingValue": "2018-09-05" },
     "dimensionsSpec": { "dimensions": ["SIG_CD", "SIG_ENG_NM", "SIG_KOR_NM"] }
   }
```
