### ISSUE TITLE
DB Connection page does not show Oracle, Phoenix, Tibero

### ISSUE THREAD

**Issue by tooptoop4** [metatron-app/metatron-discovery#934]
DB Connection page does not show Oracle, Phoenix, Tibero.

related to comments on line 432?
https://github.com/metatron-app/metatron-discovery/blob/e01b56197351a8f9272d4a15f6b2fd02436cb5ef/discovery-frontend/src/app/common/component/abstract.component.ts

**Comment by kyungtaak** [comment]
@tooptoop4 ^^; We were hiding it because we could not provide jdbc downloads of commercial software while we prepared for open source. 
We are going to reorganize the jdbc connection into an extensible structure after version 3.1. Once this structure is available, we will add connections incrementally thereafter.
