### ISSUE TITLE
documentation - any guide on how to build a new data source (ie DB2) ?

### ISSUE THREAD

**Issue by tooptoop4** [metatron-app/metatron-discovery#936]
i want to make some dev changes to add new datasource ie URL/API data or DB2 data. Any developer guide on all files needed to change?

**Comment by kyungtaak** [comment]
@tooptoop4 #934 Maybe ... Can you wait until January next year? ;;;; Or, I can briefly guide you through this comments, but if we change the structure after 3.1, you need to change it again.

**Comment by kyungtaak** [comment]
@tooptoop4 I'm sorry to long... late reply.
We have begun to support the data connection extension since version 3.2. However, it does not officially support DB2, so if you want to use it, you can implement the extension.
Please, follow this link : https://github.com/metatron-app/metatron-discovery/tree/master/discovery-extensions
