### ISSUE TITLE
Need to improve tooltip of sankey diagram

### ISSUE THREAD

**Issue by i1befree** [metatron-app/metatron-discovery#94]
**Is your feature request related to a problem? Please describe.**
Sankey diagram 에서 툴팁을 보면 value > dimension 형식으로 출력됨(예: 192 > Paris)
의미를 알기가 매우 어려움. 특히 중간의 값일 경우는 London > 192 > Paris 형태로 출력함

**Describe the solution you'd like**
실제 다른 차트와 형식을 맞춘다면, Starting City : Paris, Sum of speed : 192 와 같은 형태로 출력 되는 것이 맞음

**Describe alternatives you've considered**
현재의 다른 차트와 표현 방식을 통일 하는 것이 좋을 것 같음

**Additional context**
<img width="863" alt="improve tooltip" src="https://user-images.githubusercontent.com/526622/44832387-af72a280-ac65-11e8-8b88-665d9d857a3a.png">

**Comment by kyungtaak** [comment]
@metatron-app/design  검토 부탁드립니다.

**Comment by esezin** [comment]
@kyungtaak 
툴팁의 내용은 현재 echart에서 제공되는 대로 표시하고 있습니다. 출력 내용 변경 가능여부에 대해 개발팀과 좀 더 검토하여 답변 드리겠습니다.

**Comment by esezin** [comment]
@kyungtaak 
툴팁 출력 변경 가능 여부와 무관하게, 기획 검토 내용을 정리하자면 아래와 같은 표시 형태가 좋을 것 같습니다.
위 스크린 샷에서의 툴팁의 경우 : 
Category : Office Supplies
Sum of Quantity : 5,178
Sub Category : Paper

**Comment by AnnieHwang** [comment]
@kyungtaak @esezin  화면 통일성 차원에서 위의 방식대로 툴팁이 표출되는것이 맞을 것 같습니다.

**Comment by i1befree** [comment]
@esezin 말씀 하신 사항은 echart 에서 제공되는 대로가 아니라고 봅니다. echart 에 있는 한 예제가 제공하는 대로라고 보입니다. 일례로 같은 sankey 이지만 아래 스크린샷 첨부 드립니다. 저희와는 다른 형태의 툴팁을 제공합니다.
<img width="1137" alt="2018-09-12 9 30 46" src="https://user-images.githubusercontent.com/526622/45394982-bc809000-b66e-11e8-8404-873a8d406de8.png">

**Comment by juheeko9** [comment]
f#94-improve_sankey_tooltip 브랜치 추가하였습니다.

**Comment by juheeko9** [comment]
@kyungtaak 
센키차트일때 alias 변경 후 데이터 호출시 서버에러가 발생합니다.
확인부탁드립니다.

[API]
api/datasources/query/search

[Reuqest Body]
`
{"context":{"discovery.route.uri":"/workbook/f01503c2-84cb-4033-97c2-b8877a91cdd5","discovery.dashboard.id":"9b710c3b-8075-4abc-b928-8c6a9ebe61be"},"userFields":[{"oriColumnName":"","useChart":false,"useFilter":false,"useChartFilter":false,"type":"user_expr","role":"DIMENSION","dataSource":"sales","alias":"DIMENSION_1","name":"DIMENSION_1","expr":"\"Category\"","aggregated":false}],"dataSource":{"joins":[],"temporary":false,"id":"ds-37","name":"sales","uiDescription":"sales data (2011~2014)","type":"default","connType":"ENGINE","engineName":"sales"},"filters":[{"field":"OrderDate","dataSource":"sales","type":"time_all"}],"pivot":{"columns":[{"type":"dimension","name":"Category","subType":"STRING","subRole":"DIMENSION","alias":"Category"},{"type":"dimension","name":"Region","subType":"STRING","subRole":"DIMENSION","fieldAlias":"88region122","alias":"88region122"}],"rows":[],"aggregations":[{"type":"measure","aggregationType":"SUM","name":"Discount","subType":"DOUBLE","subRole":"MEASURE","format":{"type":"number","sign":"KRW","decimal":2,"useThousandsSep":true,"abbr":"NONE","customSymbol":null},"alias":"SUM(Discount)"}]},"limits":{"limit":100000,"sort":[]},"aliases":[{"type":"value","ref":"9b710c3b-8075-4abc-b928-8c6a9ebe61be"}],"resultFormat":{"type":"graph"}}
`

[Return]
`{"code":"EG0001","message":"Engine access error","details":"Fail to process response : [{\"error\":\"Unknown exception\",\"errorMessage\":\"Instantiation of [simple type, class io.druid.query.groupby.GroupByQuery] value failed: invalid column in grouping set [Region]\",\"errorClass\":\"com.fasterxml.jackson.databind.JsonMappingException\",\"errorStack\":[\"com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapException(StdValueInstantiator.java:405)\",\"com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:234)\",\"com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:167)\",\"com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:398)\",\"com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1064)\",\"com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:264)\",\"com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:156)\",\"com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:126)\",\"com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)\",\"com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:84)\",\"com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:132)\",\"com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:41)\",\"... more\",\"Caused by: com.google.common.base.Preconditions.checkArgument(Preconditions.java:125)\",\"io.druid.query.groupby.GroupingSetSpec$Names.validate(GroupingSetSpec.java:70)\",\"io.druid.query.groupby.GroupByQuery.<init>(GroupByQuery.java:132)\",\"sun.reflect.GeneratedConstructorAccessor114.newInstance(Unknown Source)\",\"sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)\",\"java.lang.reflect.Constructor.newInstance(Constructor.java:422)\",\"com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:125)\",\"com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:230)\",\"... more\"],\"host\":\"localhost:8082\",\"serviceName\":\"druid/broker\"}]"}`

[참고화면]
![image](https://user-images.githubusercontent.com/42233502/45526703-29cd2600-b813-11e8-9f6d-9dec0f8bb218.png)

**Comment by kyungtaak** [comment]
@juheeko9 수정하였습니다.

**Comment by juheeko9** [comment]
@kyungtaak alias를 변경 후 리턴되는 links값에서는 기존 fieldName으로 리턴되는 반면 ex) Region
nodes의 field값에서는 변경된 alias로 ex) Region123 리턴됩니다. 
nodes부분의 field부분을 alias가 기존 fieldName으로 리턴되게 수정부탁드립니다.

[API]
POST api/datasources/query/search

[Request]
`{"context":{"discovery.route.uri":"/workbook/c0610ba5-ef96-43cd-9aa3-f0df98c640af","discovery.dashboard.id":"b48bd06f-acee-46fa-aea5-4ccd19093c89"},"userFields":[],"dataSource":{"joins":[],"temporary":false,"id":"ds-37","name":"sales","uiDescription":"sales data (2011~2014)","type":"default","connType":"ENGINE","engineName":"sales"},"filters":[{"field":"OrderDate","dataSource":"sales","type":"time_all"}],"pivot":{"columns":[{"type":"dimension","name":"Category","subType":"STRING","subRole":"DIMENSION","alias":"Category"},{"type":"dimension","name":"Region","subType":"STRING","subRole":"DIMENSION","alias":"Region123","fieldAlias":"Region123"}],"rows":[],"aggregations":[{"type":"measure","aggregationType":"SUM","name":"Discount","subType":"DOUBLE","subRole":"MEASURE","format":{"type":"number","sign":"KRW","decimal":2,"useThousandsSep":true,"abbr":"NONE","customSymbol":null},"alias":"SUM(Discount)"}]},"limits":{"limit":100000,"sort":[]},"aliases":[{"type":"value","ref":"b48bd06f-acee-46fa-aea5-4ccd19093c89"}],"resultFormat":{"type":"graph"}}`

[Return]
`{"nodes":[{"field":"Region123","name":"Central","value":558.3400110155344},{"field":"Region123","name":"East","value":414.00000247359276},{"field":"Region123","name":"South","value":238.55000030994415},{"field":"Region123","name":"West","value":350.2000030428171},{"field":"Category","name":"Furniture","value":368.89000813663006},{"field":"Category","name":"Office Supplies","value":947.8000056296587},{"field":"Category","name":"Technology","value":244.40000307559967}],"links":[{"sourceField":"Category","source":"Furniture","targetField":"Region","target":"Central","value":143.04000478982925},{"sourceField":"Category","source":"Furniture","targetField":"Region","target":"East","value":92.60000184178352},{"sourceField":"Category","source":"Furniture","targetField":"Region","target":"South","value":40.35000039637089},{"sourceField":"Category","source":"Furniture","targetField":"Region","target":"West","value":92.90000110864639},{"sourceField":"Category","source":"Office Supplies","targetField":"Region","target":"Central","value":359.40000535547733},{"sourceField":"Category","source":"Office Supplies","targetField":"Region","target":"East","value":244.6999998241663},{"sourceField":"Category","source":"Office Supplies","targetField":"Region","target":"South","value":166.59999953210354},{"sourceField":"Category","source":"Office Supplies","targetField":"Region","target":"West","value":177.10000091791153},{"sourceField":"Category","source":"Technology","targetField":"Region","target":"Central","value":55.900000870227814},{"sourceField":"Category","source":"Technology","targetField":"Region","target":"East","value":76.70000080764294},{"sourceField":"Category","source":"Technology","targetField":"Region","target":"South","value":31.600000381469727},{"sourceField":"Category","source":"Technology","targetField":"Region","target":"West","value":80.2000010162592}]}`
